Update remove.yml

diff --git a/.github/workflows/remove.yml b/.github/workflows/remove.yml
--- a/.github/workflows/remove.yml
+++ b/.github/workflows/remove.yml
@@ -9,25 +9,32 @@ permissions:
   contents: write
 
 jobs:
-  process_files:
+  run-script:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+    - name: Checkout Repository
+      uses: actions/checkout@v3
+      
+    - name: Install Dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y yt-dlp sed nmap
 
-      - name: Set Git Identity
-        run: |
-          git config --global user.email "actions@github.com"
-          git config --global user.name "GitHub Actions"
-
-      - name: Delete speedtest Folder
-        run: |
-          if [ -d "speedtest/" ]; then
-            rm -rf speedtest/
-            git rm -r --cached speedtest/
-            git commit -m "Delete speedtest folder" || echo "No changes to commit"
-          else
-            echo "speedtest/ directory not found, skipping deletion"
-          fi
-        env:
-          PAT: ${{ secrets.GITHUBS_TOKEN }}
+    - name: Set Git Identity
+      run: |
+        git config --global user.email "actions@github.com"
+        git config --global user.name "GitHub Actions"
+      
+    - name: Delete speedtest Folder
+      run: |
+        if [ -d "speedtest/" ]; then
+          rm -rf speedtest/
+          git rm -r --cached speedtest/
+          git commit -m "Delete speedtest folder" || echo "No changes to commit"
+          git push
+        else
+          echo "speedtest/ directory not found, skipping deletion"
+        fi
+      env:
+        PAT: ${{ secrets.GITHUBS_TOKEN }}
